const path = require("path");
const REPO = process.env.HERMES_REPO ||
             path.resolve(__dirname, "..", "..", "..");
const md = require(path.join(REPO, "dashboard", "aux_md.js"));
const r = md.render; let fails = 0, n = 0;
function has(name, src, ...subs) { n++; const out = r(src); for (const s of subs) { if (!out.includes(s)) { fails++; console.log("FAIL", name, "\n  want:", s, "\n  got :", out); return; } } }
function not(name, src, ...subs) { n++; const out = r(src); for (const s of subs) { if (out.includes(s)) { fails++; console.log("FAIL(not)", name, "\n  has :", s, "\n  got :", out); return; } } }
has("para", "hello world", "<p>hello world</p>");
has("linebreak join", "a\nb", "<p>a<br>b</p>");
has("two paras", "a\n\nb", "<p>a</p><p>b</p>");
has("h1-h6", "# A\n#### D\n###### F", "<h1>A</h1>", "<h4>D</h4>", "<h6>F</h6>");
has("heading trailing #", "## T ##", "<h2>T</h2>");
has("hr", "a\n\n---\n\nb", "<p>a</p><hr><p>b</p>");
has("hr stars", "* * *", "<hr>");
has("ul", "- a\n- b", "<ul><li>a</li><li>b</li></ul>");
has("ol", "1. a\n2. b", "<ol><li>a</li><li>b</li></ol>");
has("ol start", "3. a\n4. b", '<ol start="3"><li>a</li><li>b</li></ol>');
has("nested", "- a\n  - a1\n  - a2\n- b", "<ul><li>a<ul><li>a1</li><li>a2</li></ul></li><li>b</li></ul>");
has("nested ol in ul", "- a\n   1. x\n   2. y\n- b", "<ul><li>a<ol><li>x</li><li>y</li></ol></li><li>b</li></ul>");
has("loose list keeps numbering", "1. a\n\n2. b\n\n3. c", "<ol><li>a</li><li>b</li><li>c</li></ol>");
has("list then para", "- a\n- b\n\nAfter.", "</ul><p>After.</p>");
has("task", "- [x] done\n- [ ] todo", '<input type="checkbox" disabled checked> done', '<input type="checkbox" disabled> todo');
has("year not list", "It happened in\n2024. It was big.", "<p>It happened in<br>2024. It was big.</p>");
has("quote", "> q1\n> q2", "<blockquote><p>q1<br>q2</p></blockquote>");
has("nested quote list", "> - a\n> - b", "<blockquote><ul><li>a</li><li>b</li></ul></blockquote>");
has("table", "| A | B |\n|---|:-:|\n| 1 | 2 |\n| 3 | 4 |", '<div class="md-table"><table><thead><tr><th>A</th><th style="text-align:center">B</th></tr></thead><tbody><tr><td>1</td><td style="text-align:center">2</td></tr><tr><td>3</td><td style="text-align:center">4</td></tr></tbody></table></div>');
has("table no outer pipes", "A | B\n--- | ---\n1 | 2", "<th>A</th><th>B</th>", "<td>1</td><td>2</td>");
has("table inline", "| `x` | **b** |\n|--|--|\n| a | b |", "<th><code>x</code></th><th><strong>b</strong></th>");
has("fence lang", "```python\nprint('hi')\n```", '<pre><code class="lang-python" data-lang="python">print(\'hi\')</code></pre>');
has("fence no lang", "```\na **b**\n```", "<pre><code>a **b**</code></pre>");
has("fence unclosed", "```js\nlet x", '<pre><code class="lang-js" data-lang="js">let x</code></pre>');
has("tilde fence", "~~~\nx\n~~~", "<pre><code>x</code></pre>");
has("code protects", "use `**not bold**` ok", "<code>**not bold**</code>");
has("bold", "**b** and __b2__", "<strong>b</strong>", "<strong>b2</strong>");
has("em", "*e* and _e2_", "<em>e</em>", "<em>e2</em>");
has("bold-em", "***x***", "<strong><em>x</em></strong>");
has("strike", "~~gone~~", "<del>gone</del>");
not("snake_case", "a snake_case_name here", "<em>");
not("math stars", "2 * 3 * 4 = 24", "<em>");
has("link", "[t](https://x.y/z_a_b)", '<a href="https://x.y/z_a_b" target="_blank" rel="noopener">t</a>');
has("bare url", "see https://x.y/p_q_r. ok", '<a href="https://x.y/p_q_r" target="_blank" rel="noopener">https://x.y/p_q_r</a>. ok');
has("image as link", "![alt](https://x.y/i.png)", '<a href="https://x.y/i.png" target="_blank" rel="noopener">alt</a>');
not("js link", "[x](javascript:alert(1))", "<a");
not("xss", "<script>alert(1)</script> <img src=x onerror=1>", "<script>", "<img");
has("xss escaped", "<b>x</b>", "&lt;b&gt;x&lt;/b&gt;");
has("quote attr", 'say "hi"', "say &quot;hi&quot;");
has("think closed", "<think>plan a\nplan b</think>\n\nAnswer.", '<details class="md-think"><summary>Reasoning</summary><p>plan a<br>plan b</p></details>', "<p>Answer.</p>");
has("think open", "<think>still", '<details class="md-think" open><summary>Reasoning…</summary><p>still</p></details>');
has("crlf", "a\r\n\r\nb", "<p>a</p><p>b</p>");
has("empty", "", "");
has("null", null, "");
has("hard break", "a  \nb\\\nc", "<p>a<br>b<br>c</p>");
has("mixed doc", "## Plan\n\nSteps:\n1. **Install** it\n2. Run `x`\n\n| k | v |\n|---|---|\n| a | 1 |\n\n> note\n\n---\nDone.", "<h2>Plan</h2><p>Steps:</p><ol><li><strong>Install</strong> it</li><li>Run <code>x</code></li></ol>", "<blockquote><p>note</p></blockquote><hr><p>Done.</p>");
console.log(`TESTS ${n - fails} passed ${fails} failed`);
process.exit(fails ? 1 : 0);
